### ISSUE TITLE
Playbook used to compile the binary?

### ISSUE THREAD

**Issue by zLupa** [XniceCraft/ffmpeg-colab#2]
want to add more external libraries on top of the one that already exists, any way to get the playbook so that I can edit it?

Also, does it support hardware acceleration with GPU? 
edit: it doesn't support

**Comment by XniceCraft** [comment]
What library you wanna add?
and what is playbook? sorry idk

**Comment by zLupa** [comment]
> 

I was trying to encode a video with Cuda support, but I think it isn't included in the FFmpeg build and also Samba support.
by the playbook I mean the code used to compile it (if you've it).
I think I don't need it anymore as I moved to Kaggle.
